# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newfile.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formNewFile(object):
    def setupUi(self, formNewFile):
        formNewFile.setObjectName("formNewFile")
        formNewFile.resize(364, 213)
        self.gridLayout = QtWidgets.QGridLayout(formNewFile)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(formNewFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(154, 153, 150);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(formNewFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBoxFileType = QtWidgets.QComboBox(formNewFile)
        self.comboBoxFileType.setObjectName("comboBoxFileType")
        self.comboBoxFileType.addItem("")
        self.comboBoxFileType.addItem("")
        self.comboBoxFileType.addItem("")
        self.comboBoxFileType.addItem("")
        self.comboBoxFileType.addItem("")
        self.comboBoxFileType.addItem("")
        self.comboBoxFileType.setItemText(5, "")
        self.verticalLayout.addWidget(self.comboBoxFileType)
        self.label_3 = QtWidgets.QLabel(formNewFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditDefaultFileName = QtWidgets.QLineEdit(formNewFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.lineEditDefaultFileName.setFont(font)
        self.lineEditDefaultFileName.setObjectName("lineEditDefaultFileName")
        self.verticalLayout.addWidget(self.lineEditDefaultFileName)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonCancel = QtWidgets.QPushButton(formNewFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonSubmit = QtWidgets.QPushButton(formNewFile)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.pushButtonSubmit.setFont(font)
        self.pushButtonSubmit.setAutoDefault(True)
        self.pushButtonSubmit.setDefault(True)
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.horizontalLayout.addWidget(self.pushButtonSubmit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(formNewFile)
        QtCore.QMetaObject.connectSlotsByName(formNewFile)

    def retranslateUi(self, formNewFile):
        _translate = QtCore.QCoreApplication.translate
        formNewFile.setWindowTitle(_translate("formNewFile", "Specify New File Type"))
        self.label_2.setText(_translate("formNewFile", "EPIC Coder"))
        self.label.setText(_translate("formNewFile", "New File Type:"))
        self.comboBoxFileType.setItemText(0, _translate("formNewFile", "Plain Text File: .txt"))
        self.comboBoxFileType.setItemText(1, _translate("formNewFile", "EPIC Production Rule File: .prs"))
        self.comboBoxFileType.setItemText(2, _translate("formNewFile", "C++ Code File: .cpp"))
        self.comboBoxFileType.setItemText(3, _translate("formNewFile", "C++ Header File: . h"))
        self.comboBoxFileType.setItemText(4, _translate("formNewFile", "Python Source File: .py"))
        self.label_3.setText(_translate("formNewFile", "Default File Name:"))
        self.lineEditDefaultFileName.setText(_translate("formNewFile", "Untitled.txt"))
        self.pushButtonCancel.setText(_translate("formNewFile", "CANCEL"))
        self.pushButtonSubmit.setText(_translate("formNewFile", "SUBMIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formNewFile = QtWidgets.QWidget()
    ui = Ui_formNewFile()
    ui.setupUi(formNewFile)
    formNewFile.show()
    sys.exit(app.exec_())
