# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'duplicateui.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DuplicateFileDialog(object):
    def setupUi(self, DuplicateFileDialog):
        DuplicateFileDialog.setObjectName("DuplicateFileDialog")
        DuplicateFileDialog.resize(725, 340)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        DuplicateFileDialog.setFont(font)
        DuplicateFileDialog.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(DuplicateFileDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DuplicateFileDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditStem = QtWidgets.QLineEdit(DuplicateFileDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.lineEditStem.setFont(font)
        self.lineEditStem.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditStem.setObjectName("lineEditStem")
        self.horizontalLayout.addWidget(self.lineEditStem)
        self.labelExt = QtWidgets.QLabel(DuplicateFileDialog)
        self.labelExt.setObjectName("labelExt")
        self.horizontalLayout.addWidget(self.labelExt)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.labelPath = QtWidgets.QLabel(DuplicateFileDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.labelPath.setFont(font)
        self.labelPath.setStyleSheet("color: rgb(94, 92, 100);")
        self.labelPath.setWordWrap(True)
        self.labelPath.setObjectName("labelPath")
        self.verticalLayout.addWidget(self.labelPath)
        self.labelError = QtWidgets.QLabel(DuplicateFileDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelError.setFont(font)
        self.labelError.setStyleSheet("color: rgb(237, 51, 59);")
        self.labelError.setWordWrap(True)
        self.labelError.setObjectName("labelError")
        self.verticalLayout.addWidget(self.labelError)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(DuplicateFileDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCancel.setFont(font)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.pushButtonSelect = QtWidgets.QPushButton(DuplicateFileDialog)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSelect.setFont(font)
        self.pushButtonSelect.setDefault(True)
        self.pushButtonSelect.setObjectName("pushButtonSelect")
        self.horizontalLayout_2.addWidget(self.pushButtonSelect)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(DuplicateFileDialog)
        QtCore.QMetaObject.connectSlotsByName(DuplicateFileDialog)

    def retranslateUi(self, DuplicateFileDialog):
        _translate = QtCore.QCoreApplication.translate
        DuplicateFileDialog.setWindowTitle(_translate("DuplicateFileDialog", "Filename For Duplicate File"))
        self.label.setText(_translate("DuplicateFileDialog", "What Name Should Be Used For The Duplicate File?"))
        self.lineEditStem.setText(_translate("DuplicateFileDialog", "myfile"))
        self.labelExt.setText(_translate("DuplicateFileDialog", ".txt"))
        self.labelPath.setText(_translate("DuplicateFileDialog", "/home/me/myfile.txt"))
        self.labelError.setText(
            _translate("DuplicateFileDialog", "That file already exists, please choose another file name.")
        )
        self.pushButtonCancel.setText(_translate("DuplicateFileDialog", "Cancel"))
        self.pushButtonSelect.setText(_translate("DuplicateFileDialog", "Select"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DuplicateFileDialog = QtWidgets.QDialog()
    ui = Ui_DuplicateFileDialog()
    ui.setupUi(DuplicateFileDialog)
    DuplicateFileDialog.show()
    sys.exit(app.exec_())
